### ISSUE TITLE
Empty txt file

### ISSUE THREAD

**Issue by ConDem94** [huynguyen250896/geneSA#1]
Hello,

I am trying to run geneSA for my analysis which includes 240 genes. I prepared the data, OS_MONTHS and OS_STATUS as required but when I run the function it creates an empty txt file.

I believe that I have significant genes in my gene list. Is there a way to fix this? Thanks!

**Comment by huynguyen250896** [comment]
Hi there,

Sorry for not getting back to you sooner. 

I just have checked the tool again and it still worked well. So I can say that an empty txt file certainly indicates that your gene list has been not included any significant genes.
However, you said that there should be some significant genes in your gene list, so I guess maybe you defined your significance level is P-value < 0.05, didn't you? The following are some important facts regarding the tool you should keep in mind:

1. The geneSA runs univariate survival analysis on individual genes of yours and automatically only keeps significant genes whose Q-value (adjusted P-values) <= 0.05. That's why your given file is empty.
2. Multiple testing correction has been included in the tool is Benjamini-Hochberg's procedure.

By the way, your raised point is very informative and useful, leading me to update the tool. Specifically, I have added two new parameters to the tool: _Pcut_ and _Qcut_, in which they decide statistical significance levels, P-value and Q-value, respectively. From that, if you do not want to set the Q-value <= 0.05 (default value), you can set it to 1 (i.e., _Qcut = 1_), so you can consider your significant genes as genes whose P-value <= 0.05. Please remember removing and re-installing the tool in order to make sure you are using the latest version of the tool before setting the parameter _Qcut = 1_. Now, it should work and you do not receive an empty list again. Nevertheless, be careful with your choice (Q-value <= 1) as 240 genes equal 240 tests and your analysis is most likely to face the type-II errors. My advice is that you can set the _Qcut = 0.1_ instead.
Check this out and reply to me if you still encounter this problem or any other problems. Thanks.
